import {launchBrowser} from './browser.mjs';import {previewURL} from './paths.mjs';import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const browser=await launchBrowser(),results=[];fs.mkdirSync('.runtime',{recursive:true});
try{for(const size of [{width:1440,height:1000},{width:390,height:844}]){const mobile=size.width<600,page=await browser.newPage({viewport:size,deviceScaleFactor:1,isMobile:mobile,hasTouch:mobile,acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const start=Date.now();await page.goto(previewURL+'/',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__APP__?.ready,null,{timeout:120000});const readyMilliseconds=Date.now()-start;
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,'Horizontal layout overflow');
const views=[];for(const view of ['front','three','side','back','face','outfit','hands','shoes']){await page.locator(`[data-view="${view}"]`).click();assert.equal(await page.evaluate(()=>window.__APP__.getStats().activeView),view);views.push(view);}
for(const mode of ['clay','wire','textured']){await page.locator(`[data-mode="${mode}"]`).click();assert.equal(await page.evaluate(()=>window.__APP__.getStats().mode),mode);}
await page.locator('#reset').click();assert.equal(await page.evaluate(()=>window.__APP__.getStats().activeView),'front');
await page.locator('#viewport').scrollIntoViewIfNeeded();const box=await page.locator('#viewport').boundingBox(),before=await page.evaluate(()=>window.__APP__.controls.getAzimuthalAngle());
const x=box.x+box.width*.45,y=box.y+box.height*.45;if(mobile){const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+70,y:y+12}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else{await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+100,y+12,{steps:8});await page.mouse.up();}await page.waitForTimeout(600);const orbitChanged=Math.abs(before-await page.evaluate(()=>window.__APP__.controls.getAzimuthalAngle()))>.001;assert.ok(orbitChanged,'Pointer/touch orbit did not move camera');
await page.locator('#reset').click();await page.locator('#rotate').click();assert.equal(await page.locator('#rotate').getAttribute('aria-pressed'),'true');await page.locator('#reset').click();assert.equal(await page.locator('#rotate').getAttribute('aria-pressed'),'false');
let downloadVerified=null,snapshotVerified=null;if(!mobile){const waiting=page.waitForEvent('download');await page.locator('#export').click();const d=await waiting;await d.saveAs('.runtime/test-download.glb');const sha=b=>crypto.createHash('sha256').update(b).digest('hex');downloadVerified=sha(fs.readFileSync('.runtime/test-download.glb'))===sha(fs.readFileSync('public/exports/gpt6_astra_pro_colabdev_web_rgirljk.glb'));assert.ok(downloadVerified,'Downloaded GLB differs from original');const shot=page.waitForEvent('download');await page.locator('#snapshot').click();await(await shot).saveAs('.runtime/test-snapshot.png');snapshotVerified=fs.readFileSync('.runtime/test-snapshot.png').subarray(0,8).toString('hex')==='89504e470d0a1a0a';assert.ok(snapshotVerified);}
await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(600);await page.screenshot({path:`public/preview/ui-${size.width}.png`,fullPage:false,timeout:120000});const stats=await page.evaluate(()=>window.__APP__.getStats());assert.equal(stats.modelSource,'prebuilt');assert.equal(errors.length,0,errors.join('\n'));results.push({size,mobileEmulation:mobile,overflow,readyMilliseconds,views,materialModes:['clay','wire','textured'],reset:true,orbitChanged,downloadVerified,snapshotVerified,errors,stats});await page.close();}
console.log(JSON.stringify(results,null,2));}finally{fs.writeFileSync('public/preview/ui-tests.json',JSON.stringify(results,null,2));await browser.close();}
