import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {buildCharacter} from './character.js';
const el=document.querySelector('#viewport'),params=new URLSearchParams(location.search),capture=params.has('capture');
if(capture)document.body.classList.add('capture');
const renderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<650?1.4:1.8));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive three-dimensional character. Drag to rotate and scroll to zoom.');renderer.domElement.setAttribute('role','img');
const scene=new T.Scene();scene.background=new T.Color(0xedece6);const pmrem=new T.PMREMGenerator(renderer);const env=pmrem.fromScene(new RoomEnvironment(),.04);scene.environment=env.texture;scene.environmentIntensity=.35;pmrem.dispose();
const camera=new T.PerspectiveCamera(24,1,.05,100);camera.position.set(.15,4.45,18.5);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(.05,3.78,0);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=1.7;controls.maxDistance=25;controls.maxPolarAngle=Math.PI*.65;controls.autoRotateSpeed=.6;controls.enablePan=true;
scene.add(new T.HemisphereLight(0xf5f3f0,0x9e887e,.65));
const key=new T.DirectionalLight(0xfff6ef,2.1);key.position.set(-3.8,10,7);key.castShadow=true;key.shadow.mapSize.set(innerWidth<650?1024:2048,innerWidth<650?1024:2048);key.shadow.camera.left=-4;key.shadow.camera.right=4;key.shadow.camera.top=8;key.shadow.camera.bottom=-1;key.shadow.camera.near=.1;key.shadow.camera.far=20;key.shadow.bias=-.00015;key.shadow.normalBias=.003;scene.add(key);key.target.position.set(0,4,0);scene.add(key.target);
const fill=new T.DirectionalLight(0xdfebff,.65);fill.position.set(4,6,3);scene.add(fill);const rim=new T.DirectionalLight(0xffffff,2.5);rim.position.set(1,9,-4);scene.add(rim);
const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshBasicMaterial({color:0xedece6,toneMapped:false}));floor.rotation.x=-Math.PI/2;floor.position.y=.028;floor.receiveShadow=false;scene.add(floor);
const sc=document.createElement('canvas');sc.width=sc.height=128;let cx=sc.getContext('2d'),grad=cx.createRadialGradient(64,64,2,64,64,63);grad.addColorStop(0,'rgba(51,48,38,.24)');grad.addColorStop(.45,'rgba(51,48,38,.10)');grad.addColorStop(1,'rgba(51,48,38,0)');cx.fillStyle=grad;cx.fillRect(0,0,128,128);let shadow=new T.Mesh(new T.PlaneGeometry(2.4,1.6),new T.MeshBasicMaterial({map:new T.CanvasTexture(sc),transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.set(0,.031,.2);scene.add(shadow);
const started=performance.now();let exportManifest=null,model=null,modelSource='procedural';try{exportManifest=await fetch('model-manifest.json').then(r=>r.ok?r.json():null);if(exportManifest?.available&&(!capture||params.has('prebuilt'))&&!params.has('procedural')){const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);const gltf=await loader.loadAsync(exportManifest.web);model=gltf.scene;modelSource='prebuilt';}}catch(err){console.warn('Prebuilt model unavailable; reconstructing original geometry.',err.message);}if(!model)model=buildCharacter();let meshCount=0;model.traverse(o=>{if(o.isMesh)meshCount++;});const modelLoadMilliseconds=performance.now()-started;model.traverse(m=>{if(m.isMesh&&m.material.name.includes('hair')){m.material.side=T.DoubleSide;if(m.material.alphaTest>0)m.material.alphaToCoverage=false;}});scene.add(model);
const originals=new Map();let triangles=0;model.traverse(m=>{if(m.isMesh){originals.set(m,m.material);triangles+=(m.geometry.index?m.geometry.index.count:m.geometry.attributes.position.count)/3;}});
let dirty=true,rotating=false,activeView='front',mode='textured',frames=0,last=performance.now(),fps=0;
function resize(){document.querySelector('.stage-footnote span').textContent=innerWidth<600?'Drag to orbit · Pinch to zoom':'Drag to orbit · Scroll to zoom';const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();dirty=true;}new ResizeObserver(resize).observe(el);resize();
const keyOffset=key.position.clone().sub(key.target.position);
function configureShadowView(name){
 const portrait=name.startsWith('face');
 const specs=portrait?[[.245,6.77,.12],1.28]:name==='outfit'?[[.05,4.95,0],1.8]:name==='hands'?[[0,4.35,-.4],1.1]:name==='shoes'?[[0,.55,.2],1.0]:[[0,3.8,0],4.2];
 key.target.position.set(...specs[0]);key.position.copy(key.target.position).add(keyOffset);const c=key.shadow.camera,r=specs[1];c.left=-r;c.right=r;c.top=r;c.bottom=-r;c.updateProjectionMatrix();
 key.shadow.normalBias=portrait?.0013:.0020;key.shadow.radius=portrait?4.0:2.5;key.shadow.bias=-.00004;key.shadow.needsUpdate=true;renderer.shadowMap.needsUpdate=true;
}
function inspectSurface(x,y){
 const bounds=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2(x/bounds.width*2-1,1-y/bounds.height*2),camera);
 return ray.intersectObject(model,true).slice(0,4).map(hit=>({material:hit.object.material.name,part:hit.object.userData.partRanges?.find(p=>hit.faceIndex>=p.firstTriangle&&hit.faceIndex<p.firstTriangle+p.triangleCount)?.name||hit.object.name,point:hit.point.toArray(),normal:hit.face.normal.clone().transformDirection(hit.object.matrixWorld).toArray(),faceIndex:hit.faceIndex,uv:hit.uv?.toArray()}));
}
function setView(name){configureShadowView(name);activeView=name;controls.autoRotate=false;rotating=false;const damping=controls.enableDamping;controls.enableDamping=false;controls.update();controls.enableDamping=damping;document.querySelector('#rotate').classList.remove('active');document.querySelector('#rotate').setAttribute('aria-pressed','false');const p={front:[[.1,6.85,18.8],[.07,3.8,0]],three:[[9.4,6.6,16.9],[.07,3.8,0]],side:[[20,6.6,.1],[0,3.8,0]],back:[[.0,6.6,-20],[0,3.8,0]],face:[[.28,7.04,4.1],[.27,6.88,.05]],faceThree:[[2.0,7.02,3.7],[.245,6.84,.09]],faceSide:[[4.1,7.0,.15],[.245,6.84,.09]],outfit:[[.05,5.1,6.8],[.05,4.9,0]],hands:[[-2.8,4.5,-4.5],[0,4.35,-.4]],shoes:[[1.9,1.8,4.4],[0,.55,.2]]}[name]||[[.1,4,18.4],[.07,3.8,0]];camera.position.set(...p[0]);controls.target.set(...p[1]);controls.update();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelector('#view-label').textContent=name==='three'?'THREE-QUARTER VIEW':name.toUpperCase()+' VIEW';dirty=true;}
function setMode(next){mode=next;model.traverse(m=>{if(!m.isMesh)return;if(next==='clay'){if(!m.userData.clay)m.userData.clay=new T.MeshStandardMaterial({color:0xc5beac,roughness:.72,side:T.DoubleSide});m.material=m.userData.clay;}else{m.material=originals.get(m);m.material.wireframe=next==='wire';}});document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===next));dirty=true;}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
async function bakeOcclusion(options={}){
 setMode('textured');const {bakeContactOcclusion}=await import('./occlusion.js');
 const report=await bakeContactOcclusion(model,options);
 model.traverse(o=>{if(o.isMesh)originals.set(o,o.material);});dirty=true;return report;
}
async function exportGLB(save=true){setMode('textured');const e=new GLTFExporter();const buf=await e.parseAsync(model,{binary:true,onlyVisible:true});if(save)download(new Blob([buf],{type:'model/gltf-binary'}),'gpt6_astra_pro_colabdev_web_rgirljk.glb');return buf;}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
document.querySelector('#rotate').addEventListener('click',e=>{rotating=!rotating;controls.autoRotate=rotating;e.currentTarget.classList.toggle('active',rotating);e.currentTarget.setAttribute('aria-pressed',rotating);dirty=true;});
document.querySelector('#reset').addEventListener('click',()=>{setMode('textured');setView('front');});document.querySelector('#export').addEventListener('click',async e=>{const b=e.currentTarget;if(exportManifest?.available&&!params.has('procedural')){const a=document.createElement('a');a.href=exportManifest.source;a.download='gpt6_astra_pro_colabdev_web_rgirljk.glb';a.click();return;}b.disabled=true;b.textContent='Preparing...';try{await exportGLB();}catch(err){document.querySelector('#notice').textContent='Export failed: '+err.message;}finally{b.disabled=false;b.textContent='Export model ↗';}});
document.querySelector('#snapshot').addEventListener('click',()=>{renderer.render(scene,camera);renderer.domElement.toBlob(b=>download(b,'gpt6_astra_pro_web_portrait.png'));});document.querySelector('#fullscreen').addEventListener('click',()=>{if(document.fullscreenElement)document.exitFullscreen();else el.parentElement.requestFullscreen();});
controls.addEventListener('change',()=>dirty=true);document.addEventListener('visibilitychange',()=>dirty=true);
function tick(){requestAnimationFrame(tick);if(document.hidden&&!capture)return;controls.update();if(dirty||rotating){renderer.render(scene,camera);dirty=false;frames++;}let now=performance.now();if(now-last>2000){fps=Math.round(frames*1000/(now-last));frames=0;last=now;}}
setView(params.get('view')||'front');tick();
document.querySelector('#polycount').textContent=Math.round(triangles/1000)+'k';document.querySelector('#drawcount').textContent=meshCount;document.querySelector('#load-time').textContent=((performance.now()-started)/1000).toFixed(1)+'s';document.querySelector('#loader').classList.add('done');
window.__APP__={ready:true,model,renderer,scene,camera,controls,setView,setMode,exportGLB,inspectSurface,bakeOcclusion,getStats:()=>({triangles,drawCalls:meshCount,modelSource,modelLoadMilliseconds,occlusion:model.userData.contactOcclusion??null,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,mode,activeView,render:renderer.info.render})};
let version=null;async function refresh(){try{const [v,p]=await Promise.all([fetch('version.json?t='+Date.now()).then(r=>r.json()),fetch('progress.json?t='+Date.now()).then(r=>r.json())]);if(version&&version!==v.builtAt){location.reload();return;}version=v.builtAt;document.querySelector('#revision').textContent='REV '+String(p.iteration).padStart(2,'0');document.querySelector('#score').textContent=p.score===null?'Pending review':p.score+'/100';document.querySelector('#score-note').textContent=p.note;document.querySelector('#review-count').textContent=p.iteration+' completed reviews';document.querySelector('#journal-items').innerHTML=p.revisions.slice().reverse().map(r=>`<article class="journal-card"><div class="journal-top"><span>REV ${String(r.iteration).padStart(2,'0')}</span><span>${r.score===null?'Unrated':r.score+'/100'}</span></div>${r.image?`<a href="${r.image}" target="_blank"><img src="${r.image}" alt="Revision ${r.iteration} browser capture" loading="lazy"></a>`:''}${r.views?.length?`<details class="angle-list"><summary>${r.views.length} captured views</summary>${r.views.map(v=>`<a href="${v.path}" target="_blank">${v.label} ↗</a><code>/build/gpt6_astra_pro_colabdev_web_rgirljk/${v.path}</code>`).join('')}</details>`:''}<h3>${r.title}</h3><p>${r.notes}</p>${r.image?`<code>/build/gpt6_astra_pro_colabdev_web_rgirljk/${r.image}</code>`:''}</article>`).join('');}catch(e){console.debug('Journal unavailable',e);}}
refresh();if(!capture)setInterval(refresh,7000);

if(params.has('ao')&&!model.userData.contactOcclusion){window.__APP__.ready=false;try{window.__APP__.occlusionReport=await bakeOcclusion({samples:24,radius:.18,strength:.60,region:'head'});}finally{window.__APP__.ready=true;}}
