import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {buildCharacter} from './character.js';
const el=document.querySelector('#viewport'),params=new URLSearchParams(location.search),capture=params.has('capture');
if(capture)document.body.classList.add('capture');
const renderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive three-dimensional character. Drag to rotate and scroll to zoom.');renderer.domElement.setAttribute('role','img');
const scene=new T.Scene();scene.background=new T.Color(0xedece6);const pmrem=new T.PMREMGenerator(renderer);const env=pmrem.fromScene(new RoomEnvironment(),.04);scene.environment=env.texture;scene.environmentIntensity=.43;pmrem.dispose();
const camera=new T.PerspectiveCamera(28,1,.05,100);camera.position.set(.15,4.45,18.5);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(.05,3.78,0);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=1.7;controls.maxDistance=25;controls.maxPolarAngle=Math.PI*.65;controls.autoRotateSpeed=.6;controls.enablePan=true;
scene.add(new T.HemisphereLight(0xf3f4ff,0xc6b3a0,1.35));
const key=new T.DirectionalLight(0xfff2e1,2.65);key.position.set(-3.5,9,6);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-4;key.shadow.camera.right=4;key.shadow.camera.top=8;key.shadow.camera.bottom=-1;key.shadow.camera.near=.1;key.shadow.camera.far=20;key.shadow.bias=-.00015;key.shadow.normalBias=.003;scene.add(key);key.target.position.set(0,4,0);scene.add(key.target);
const fill=new T.DirectionalLight(0xd4e5ff,1.15);fill.position.set(4,6,3);scene.add(fill);const rim=new T.DirectionalLight(0xffffff,2.2);rim.position.set(1,9,-4);scene.add(rim);
const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshBasicMaterial({color:0xedece6,toneMapped:false}));floor.rotation.x=-Math.PI/2;floor.position.y=.028;floor.receiveShadow=false;scene.add(floor);
const sc=document.createElement('canvas');sc.width=sc.height=128;let cx=sc.getContext('2d'),grad=cx.createRadialGradient(64,64,2,64,64,63);grad.addColorStop(0,'rgba(51,48,38,.24)');grad.addColorStop(.45,'rgba(51,48,38,.10)');grad.addColorStop(1,'rgba(51,48,38,0)');cx.fillStyle=grad;cx.fillRect(0,0,128,128);let shadow=new T.Mesh(new T.PlaneGeometry(2.4,1.6),new T.MeshBasicMaterial({map:new T.CanvasTexture(sc),transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.set(0,.031,.2);scene.add(shadow);
const started=performance.now();const model=buildCharacter();model.traverse(m=>{if(m.isMesh&&m.material.name.includes('hair'))m.material.side=T.DoubleSide;});scene.add(model);
const originals=new Map();let triangles=0;model.traverse(m=>{if(m.isMesh){originals.set(m,m.material);triangles+=m.geometry.attributes.position.count/3;}});
let dirty=true,rotating=false,activeView='front',mode='textured',frames=0,last=performance.now(),fps=0;
function resize(){const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();dirty=true;}new ResizeObserver(resize).observe(el);resize();
function setView(name){activeView=name;controls.autoRotate=false;rotating=false;const p={front:[[.1,4.0,18.4],[.07,3.8,0]],three:[[9,5.4,16],[.07,3.8,0]],side:[[18,4.3,.1],[0,3.8,0]],back:[[.0,4.4,-18.4],[0,3.8,0]],face:[[.16,6.99,3.5],[.15,6.86,0]],hands:[[-2.8,4.5,-4.5],[0,4.35,-.4]],shoes:[[1.9,1.8,4.4],[0,.55,.2]]}[name]||[[.1,4,18.4],[.07,3.8,0]];camera.position.set(...p[0]);controls.target.set(...p[1]);controls.update();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelector('#view-label').textContent=name==='three'?'THREE-QUARTER VIEW':name.toUpperCase()+' VIEW';dirty=true;}
function setMode(next){mode=next;model.traverse(m=>{if(!m.isMesh)return;if(next==='clay'){if(!m.userData.clay)m.userData.clay=new T.MeshStandardMaterial({color:0xc5beac,roughness:.72,side:T.DoubleSide});m.material=m.userData.clay;}else{m.material=originals.get(m);m.material.wireframe=next==='wire';}});document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===next));dirty=true;}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
async function exportGLB(save=true){setMode('textured');const e=new GLTFExporter();const buf=await e.parseAsync(model,{binary:true,onlyVisible:true});if(save)download(new Blob([buf],{type:'model/gltf-binary'}),'gpt6_astra_pro_colabdev_web_rgirljk.glb');return buf;}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
document.querySelector('#rotate').addEventListener('click',e=>{rotating=!rotating;controls.autoRotate=rotating;e.currentTarget.classList.toggle('active',rotating);e.currentTarget.setAttribute('aria-pressed',rotating);dirty=true;});
document.querySelector('#reset').addEventListener('click',()=>{setMode('textured');setView('front');});document.querySelector('#export').addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;b.textContent='Preparing...';try{await exportGLB();}catch(err){document.querySelector('#notice').textContent='Export failed: '+err.message;}finally{b.disabled=false;b.textContent='Export model ↗';}});
document.querySelector('#snapshot').addEventListener('click',()=>{renderer.render(scene,camera);renderer.domElement.toBlob(b=>download(b,'gpt6_astra_pro_web_portrait.png'));});document.querySelector('#fullscreen').addEventListener('click',()=>{if(document.fullscreenElement)document.exitFullscreen();else el.parentElement.requestFullscreen();});
controls.addEventListener('change',()=>dirty=true);document.addEventListener('visibilitychange',()=>dirty=true);
function tick(){requestAnimationFrame(tick);if(document.hidden&&!capture)return;controls.update();if(dirty||rotating||capture){renderer.render(scene,camera);dirty=false;frames++;}let now=performance.now();if(now-last>2000){fps=Math.round(frames*1000/(now-last));frames=0;last=now;}}
setView(params.get('view')||'front');tick();
document.querySelector('#polycount').textContent=Math.round(triangles/1000)+'k';document.querySelector('#drawcount').textContent=model.children.length;document.querySelector('#load-time').textContent=((performance.now()-started)/1000).toFixed(1)+'s';document.querySelector('#loader').classList.add('done');
window.__APP__={ready:true,model,renderer,scene,camera,controls,setView,setMode,exportGLB,getStats:()=>({triangles,drawCalls:model.children.length,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,mode,activeView,render:renderer.info.render})};
let version=null;async function refresh(){try{const [v,p]=await Promise.all([fetch('version.json?t='+Date.now()).then(r=>r.json()),fetch('progress.json?t='+Date.now()).then(r=>r.json())]);if(version&&version!==v.builtAt){location.reload();return;}version=v.builtAt;document.querySelector('#revision').textContent='REV '+String(p.iteration).padStart(2,'0');document.querySelector('#score').textContent=p.score===null?'Pending review':p.score+'/100';document.querySelector('#score-note').textContent=p.note;document.querySelector('#review-count').textContent=p.iteration+' completed reviews';document.querySelector('#journal-items').innerHTML=p.revisions.slice().reverse().map(r=>`<article class="journal-card"><div class="journal-top"><span>REV ${String(r.iteration).padStart(2,'0')}</span><span>${r.score===null?'Unrated':r.score+'/100'}</span></div>${r.image?`<a href="${r.image}" target="_blank"><img src="${r.image}" alt="Revision ${r.iteration} browser capture" loading="lazy"></a>`:''}<h3>${r.title}</h3><p>${r.notes}</p>${r.image?`<code>/build/gpt6_astra_pro_colabdev_web_rgirljk/${r.image}</code>`:''}</article>`).join('');}catch(e){console.debug('Journal unavailable',e);}}
refresh();if(!capture)setInterval(refresh,7000);
