import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
export const V=(p)=>new T.Vector3(...p);
export const clamp=T.MathUtils.clamp, mix=T.MathUtils.lerp;
export function sample(rows,t){let k=0;while(k<rows.length-2&&t>rows[k+1][0])k++;const a=rows[k],b=rows[k+1],u=clamp((t-a[0])/(b[0]-a[0]),0,1),s=u*u*(3-2*u);return a.slice(1).map((v,i)=>mix(v,b[i+1],s));}
export function surface(name,nu,nv,fn,mat,parent){const p=[],uv=[],idx=[],col=[];for(let j=0;j<=nv;j++)for(let i=0;i<=nu;i++){const q=fn(i/nu,j/nv);p.push(...q.slice(0,3));uv.push(i/nu,j/nv);if(q.length>3)col.push(...q.slice(3,6));}for(let j=0;j<nv;j++)for(let i=0;i<nu;i++){let a=j*(nu+1)+i,b=a+nu+1;idx.push(a,a+1,b,b,a+1,b+1);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));if(col.length)g.setAttribute('color',new T.Float32BufferAttribute(col,3));g.setIndex(idx);g.computeVertexNormals();const m=new T.Mesh(g,mat);m.name=name;m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
export function ball(name,p,s,mat,parent,seg=32){const m=new T.Mesh(new T.SphereGeometry(1,seg,24),mat);m.name=name;m.position.set(...p);m.scale.set(...s);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
export function box(name,p,s,mat,parent,r=.03){const m=new T.Mesh(new RoundedBoxGeometry(...s,3,r),mat);m.name=name;m.position.set(...p);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
export function tube(name,pts,r,mat,parent,seg=48,rad=8){const c=new T.CatmullRomCurve3(pts.map(V));const g=new T.TubeGeometry(c,seg,r,rad,false);const m=new T.Mesh(g,mat);m.name=name;m.castShadow=true;parent.add(m);return m;}
export function sweep(name,pts,radii,mat,parent,segments=48,sides=24,ellip=1){const c=new T.CatmullRomCurve3(pts.map(V));const f=c.computeFrenetFrames(segments,false);return surface(name,sides,segments,(u,v)=>{const p=c.getPointAt(v),i=Math.min(segments,Math.round(v*segments)),r=sample(radii,v)[0];p.addScaledVector(f.normals[i],Math.cos(u*Math.PI*2)*r);p.addScaledVector(f.binormals[i],Math.sin(u*Math.PI*2)*r*ellip);return p.toArray();},mat,parent);}
export function loft(name,rows,mat,parent,nu=64,nv=80,modify=null){return surface(name,nu,nv,(u,v)=>{const y=mix(rows[0][0],rows.at(-1)[0],v),[x,z,rx,rz]=sample(rows,y),a=u*Math.PI*2;let p=[x+rx*Math.sin(a),y,z+rz*Math.cos(a)];return modify?modify(p,a,v,rx,rz):p;},mat,parent);}
export function patch(name,rows,mat,parent,nu=16,nv=32){return surface(name,nu,nv,(u,v)=>{const [x,y,z,w]=sample(rows,v);return [x+(u-.5)*w,y,z+.018*Math.sin(u*Math.PI)];},mat,parent);}
export function bake(root){root.updateMatrixWorld(true);const groups=new Map();root.traverse(o=>{if(!o.isMesh)return;let key=o.material.uuid+'|'+(o.geometry.attributes.color?'color':'plain');let e=groups.get(key);if(!e){e={mat:o.material,g:[],names:[]};groups.set(key,e);}let g=o.geometry.clone().applyMatrix4(o.matrixWorld);if(g.index)g=g.toNonIndexed();for(const k of Object.keys(g.attributes))if(!['position','normal','uv','color'].includes(k))g.deleteAttribute(k);e.g.push(g);e.names.push(o.name);});const out=new T.Group();out.name='RGIRLJK_original_procedural_character';for(const e of groups.values()){const m=new T.Mesh(mergeGeometries(e.g,false),e.mat);m.name=e.mat.name;m.castShadow=true;m.receiveShadow=true;m.userData.parts=e.names;out.add(m);e.g.forEach(g=>g.dispose());}return out;}
